// Windows Terminal pixel shader: "Aurora Lines" (self-contained background)
// The shader paints the entire screen (dark night sky + stars + realistic aurora) and
// composites the terminal text on top. Because every pixel is generated by
// the shader, the thin un-celled strip Terminal can leave at the edges is
// filled too -- no black line, regardless of aspect ratio.
//
// NOTE: For the true-aurora look, this profile should NOT use a
// `backgroundImage` (otherwise the image is treated as content and hides the
// aurora). A solid dark color scheme works best.

Texture2D shaderTexture;
SamplerState samplerState;

cbuffer PixelShaderSettings
{
    float  Time;
    float  Scale;
    float2 Resolution;
    float4 Background;
};

// ---- Hash / noise helpers -------------------------------------------------

float hash21(float2 p)
{
    p = frac(p * float2(123.34, 345.45));
    p += dot(p, p + 34.345);
    return frac(p.x * p.y);
}

float valueNoise(float2 p)
{
    float2 i = floor(p);
    float2 f = frac(p);
    float2 u = f * f * (3.0 - 2.0 * f);

    float a = hash21(i + float2(0.0, 0.0));
    float b = hash21(i + float2(1.0, 0.0));
    float c = hash21(i + float2(0.0, 1.0));
    float d = hash21(i + float2(1.0, 1.0));

    return lerp(lerp(a, b, u.x), lerp(c, d, u.x), u.y);
}

float fbm(float2 p)
{
    float sum = 0.0;
    float amp = 0.5;
    float2x2 rot = float2x2(0.80, -0.60, 0.60, 0.80);
    for (int i = 0; i < 5; i++)
    {
        sum += amp * valueNoise(p);
        p = mul(rot, p) * 2.0;
        amp *= 0.5;
    }
    return sum;
}

// ---- Aurora ---------------------------------------------------------------

float3 auroraColor(float2 uv)
{
    float t = Time * 0.04;
    float aspect = Resolution.x / Resolution.y;
    float2 p = float2(uv.x * aspect, uv.y);

    float3 finalColor = float3(0.0, 0.0, 0.0);

    const int LAYERS = 3;
    for (int i = 0; i < LAYERS; i++)
    {
        float fi = (float)i;
        float layerTime = t * (1.0 + fi * 0.2);
        
        // Base curve of the curtain: creates a wavy baseline
        float curve = sin(p.x * (1.2 + fi * 0.3) + layerTime) * 0.15 
                    + sin(p.x * (2.5 - fi * 0.2) - layerTime * 1.1) * 0.1;
        
        // Add organic noise to make the bottom edge less perfect/smooth
        // Use valueNoise instead of fbm to save performance
        curve += (valueNoise(float2(p.x * 3.0 + fi, layerTime * 0.5)) - 0.5) * 0.2;
        
        // Shift each layer vertically
        float curtainCenter = 0.4 + fi * 0.1 + curve;
        float dist = p.y - curtainCenter;
        
        // Profile: sharp drop below the curtain, long fade above
        // This ensures it doesn't go to the top line equally
        float profile = 0.0;
        if (dist > 0.0) {
            profile = exp(-dist * 40.0); // sharp bottom edge
        } else {
            profile = exp(dist * (5.0 + fi * 1.0)); // smooth top fade
        }
        
        // Rays: stretch X heavily to get vertical lines, warp with noise
        // Use valueNoise instead of fbm for the warp to save performance
        float2 rayPos = float2(p.x * (12.0 + fi * 2.0) + valueNoise(p * 3.0 + layerTime) * 2.0 - layerTime * 5.0, p.y * 0.5);
        
        // Use fewer octaves for the rays to save performance
        float rays = valueNoise(rayPos) * 0.5 + valueNoise(rayPos * 2.0) * 0.25;
        
        // Make the rays look like discrete lines rather than vapor
        rays = smoothstep(0.1, 0.8, rays);
        rays = pow(rays, 3.0) * 3.0;
        
        // Add some high frequency noise to the rays for texture
        // Removed to save performance, as it's a subtle effect
        
        // Add a cheap base glow so the curtain isn't completely black between rays
        float intensity = profile * (rays + 0.15);
        
        // Colors - shift slightly based on X position and time for a richer look
        float3 baseColor;
        float colorShift = sin(p.x * 2.0 + layerTime) * 0.5 + 0.5;
        if (i == 0) baseColor = lerp(float3(0.15, 0.95, 0.45), float3(0.05, 0.8, 0.6), colorShift); // Green to Teal
        else if (i == 1) baseColor = lerp(float3(0.05, 0.8, 0.6), float3(0.2, 0.4, 0.8), colorShift); // Teal to Blue
        else baseColor = lerp(float3(0.4, 0.2, 0.9), float3(0.8, 0.1, 0.5), colorShift);              // Purple to Pink
        
        // Top fade color (reddish/pinkish as seen in real auroras)
        float topFade = smoothstep(0.0, -0.5, dist); 
        float3 topColor = float3(0.8, 0.15, 0.4); 
        
        float3 layerColor = lerp(baseColor, topColor, topFade) * intensity;
        
        finalColor += layerColor * (1.0 - fi * 0.25);
    }

    return finalColor;
}

float4 main(float4 pos : SV_POSITION, float2 tex : TEXCOORD) : SV_TARGET
{
    float2 uv = tex;

    float4 base = shaderTexture.Sample(samplerState, tex);

    // Very dark night-sky gradient with a richer deep blue/purple cast at the top.
    float3 sky = lerp(float3(0.002, 0.004, 0.010),
                      float3(0.010, 0.015, 0.035),
                      1.0 - uv.y);

    // Realistic aurora on top of the sky.
    float3 bg = sky + auroraColor(uv) * 0.7;

    // Fade the background to black toward the edges, with a noise-warped
    // boundary so it reads as organic rather than a clean rectangle. This
    // also hides the thin un-celled black strip Terminal leaves at the edges.
    float2 dd = min(uv, 1.0 - uv);                 // distance to nearest edge
    float ne = min(dd.x, dd.y);
    // Use valueNoise instead of fbm to save performance
    ne += (valueNoise(uv * 3.0 + Time * 0.04) - 0.5) * 0.06; // wavy, natural border
    float edge = smoothstep(0.0, 0.14, ne);
    bg *= edge;

    // Composite the terminal content (text) over the generated background.
    // Anything brighter than near-black is treated as text and kept on top.
    float luma = dot(base.rgb, float3(0.299, 0.587, 0.114));
    float textMask = smoothstep(0.04, 0.22, luma);

    float3 result = lerp(bg, base.rgb, textMask);

    return float4(saturate(result), 1.0);
}
