// Windows Terminal pixel shader: "Aurora" (self-contained background)
// The shader paints the entire screen (dark night sky + subtle aurora) and
// composites the terminal text on top. Because every pixel is generated by
// the shader, the thin un-celled strip Terminal can leave at the edges is
// filled too -- no black line, regardless of aspect ratio.
//
// NOTE: For the true-aurora look, this profile should NOT use a
// `backgroundImage` (otherwise the image is treated as content and hides the
// aurora). A solid dark color scheme works best.

Texture2D shaderTexture;
SamplerState samplerState;

cbuffer PixelShaderSettings
{
    float  Time;
    float  Scale;
    float2 Resolution;
    float4 Background;
};

// ---- Hash / noise helpers -------------------------------------------------

float hash21(float2 p)
{
    p = frac(p * float2(123.34, 345.45));
    p += dot(p, p + 34.345);
    return frac(p.x * p.y);
}

float valueNoise(float2 p)
{
    float2 i = floor(p);
    float2 f = frac(p);
    float2 u = f * f * (3.0 - 2.0 * f);

    float a = hash21(i + float2(0.0, 0.0));
    float b = hash21(i + float2(1.0, 0.0));
    float c = hash21(i + float2(0.0, 1.0));
    float d = hash21(i + float2(1.0, 1.0));

    return lerp(lerp(a, b, u.x), lerp(c, d, u.x), u.y);
}

float fbm(float2 p)
{
    float sum = 0.0;
    float amp = 0.5;
    float2x2 rot = float2x2(0.80, -0.60, 0.60, 0.80);
    for (int i = 0; i < 5; i++)
    {
        sum += amp * valueNoise(p);
        p = mul(rot, p) * 2.0;
        amp *= 0.5;
    }
    return sum;
}

// ---- Aurora ---------------------------------------------------------------

float3 auroraColor(float2 uv)
{
    float t = Time * 0.07;

    // Aspect-correct so curtains aren't stretched on wide windows.
    float aspect = Resolution.x / Resolution.y;
    float2 p = float2(uv.x * aspect, uv.y);

    // Domain warp for slow folding/shimmer.
    float2 q = float2(p.x * 2.2, p.y * 1.6);
    q += float2(fbm(q + t), fbm(q - t)) * 0.5;

    // Sparser, thinner ribbons -> aurora occupies less of the screen.
    float bands = fbm(q + float2(0.0, t * 2.0));
    bands = pow(saturate(bands), 2.6);

    // Hang the curtains from the top and fade out by the upper-middle, so
    // most of the terminal stays clear and dark.
    float height = smoothstep(0.62, 0.08, uv.y);
    float curtain = bands * height;

    // Green-dominant aurora: teal <-> green shimmer, with subtle violet tips
    // only on the brightest parts of the ribbons.
    float3 green  = float3(0.10, 0.95, 0.45);
    float3 teal   = float3(0.05, 0.75, 0.55);
    float3 violet = float3(0.40, 0.20, 0.75);
    float3 col = lerp(teal, green, 0.5 + 0.5 * sin(t * 1.3 + uv.x * 4.0));
    col = lerp(col, violet, saturate(bands * 0.7));

    return col * curtain;
}

float4 main(float4 pos : SV_POSITION, float2 tex : TEXCOORD) : SV_TARGET
{
    float2 uv = tex;

    float4 base = shaderTexture.Sample(samplerState, tex);

    // Very dark night-sky gradient with a faint green-blue cast at the top.
    float3 sky = lerp(float3(0.004, 0.008, 0.020),
                      float3(0.010, 0.030, 0.040),
                      1.0 - uv.y);

    // Subtle aurora on top of the sky.
    float3 bg = sky + auroraColor(uv) * 0.5;

    // Fade the background to black toward the edges, with a noise-warped
    // boundary so it reads as organic rather than a clean rectangle. This
    // also hides the thin un-celled black strip Terminal leaves at the edges.
    float2 dd = min(uv, 1.0 - uv);                 // distance to nearest edge
    float ne = min(dd.x, dd.y);
    ne += (fbm(uv * 3.0 + Time * 0.04) - 0.5) * 0.06; // wavy, natural border
    float edge = smoothstep(0.0, 0.14, ne);
    bg *= edge;

    // Composite the terminal content (text) over the generated background.
    // Anything brighter than near-black is treated as text and kept on top.
    float luma = dot(base.rgb, float3(0.299, 0.587, 0.114));
    float textMask = smoothstep(0.04, 0.22, luma);

    float3 result = lerp(bg, base.rgb, textMask);

    return float4(saturate(result), 1.0);
}
